# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RankAppSwift' do

  use_frameworks!

	pod 'IQKeyboardManagerSwift', '4.0.6'
	pod 'MBProgressHUD', '~> 0.9.2'
	pod 'SDWebImage'
   	pod 'Fabric'
	pod 'TwitterKit'
	pod 'TwitterCore'
	pod 'MagicalRecord/Shorthand'

  # Pods for RankAppSwift

end
